version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            user: postgres
            password: postgres
            database: dellstore
            schema: public
            migrations: false
            ssl: false
  
  postgres:
    image: aa8y/postgres-dataset:dellstore
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: